services:
  - type: web
    name: fbp-leninogorsk
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn myproject.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
