# Generated by Django 5.1.5 on 2025-10-09 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ВидыВыплат',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Название', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Документ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Название', models.CharField(max_length=100)),
                ('ДатаСоздания', models.DateField()),
                ('Ссылка', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Организация',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ПолноеНаименование', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Отдел',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Название', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ТипыДокументов',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Название', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Выплаты',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Статус', models.CharField(blank=True, max_length=50, null=True)),
                ('Сумма', models.DecimalField(decimal_places=2, max_digits=15)),
                ('Вид', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.видывыплат')),
                ('Документ', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.документ')),
            ],
        ),
        migrations.AddField(
            model_name='документ',
            name='Организация',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.организация'),
        ),
        migrations.CreateModel(
            name='Пользователь',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Имя', models.CharField(max_length=50)),
                ('Фамилия', models.CharField(max_length=50)),
                ('Отчество', models.CharField(blank=True, max_length=50, null=True)),
                ('Роль', models.CharField(blank=True, max_length=50, null=True)),
                ('Логин', models.CharField(max_length=50, unique=True)),
                ('Пароль', models.CharField(max_length=100)),
                ('Телефон', models.CharField(blank=True, max_length=20, null=True)),
                ('Фото', models.ImageField(blank=True, null=True, upload_to='user_photos/')),
                ('Отдел', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.отдел')),
            ],
        ),
        migrations.AddField(
            model_name='документ',
            name='Автор',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.пользователь'),
        ),
        migrations.AddField(
            model_name='документ',
            name='Тип',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.типыдокументов'),
        ),
    ]
