# Generated by Django 5.1.5 on 2025-10-09 18:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='организация',
            name='ИНН',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='ИНН должен содержать ровно 10 цифр.', regex='^\\d{10}$')]),
        ),
        migrations.AddField(
            model_name='организация',
            name='Логин',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='организация',
            name='Пароль',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='организация',
            name='СчетОрганизации',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Счет организации должен содержать ровно 20 цифр.', regex='^\\d{20}$')]),
        ),
    ]
