# Generated by Django 5.1.5 on 2025-10-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_alter_организация_пароль_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='организация',
            name='Логин',
            field=models.CharField(default='default_login', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
