# Generated by Django 5.1.5 on 2025-10-12 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_alter_организация_логин'),
    ]

    operations = [
        migrations.CreateModel(
            name='Заявка',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('дата_подачи', models.DateTimeField(auto_now_add=True, verbose_name='Дата подачи')),
                ('полное_наименование', models.CharField(max_length=200, verbose_name='Полное наименование организации')),
                ('инн', models.CharField(max_length=10, verbose_name='ИНН')),
                ('счет_организации', models.CharField(max_length=20, verbose_name='Счет организации')),
                ('получатель', models.CharField(default='Муниципальное казённое учреждение «Финансово-бюджетная палата» муниципального образования «Лениногорский муниципальный район» Республики Татарстан', max_length=300)),
                ('счет_получателя', models.CharField(default='03100643000000011100', max_length=20)),
                ('другой_вид_выплаты', models.CharField(blank=True, max_length=200, null=True, verbose_name='Другой вид выплаты')),
                ('запрашиваемая_сумма', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Запрашиваемая сумма')),
                ('статус', models.CharField(choices=[('new', 'Новая'), ('approved', 'Принята'), ('rejected', 'Отклонена')], default='new', max_length=10, verbose_name='Статус')),
                ('дата_рассмотрения', models.DateTimeField(blank=True, null=True, verbose_name='Дата рассмотрения')),
                ('вид_выплаты', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.видывыплат', verbose_name='Вид выплаты')),
                ('организация', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.организация', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-дата_подачи'],
            },
        ),
    ]
