# Generated by Django 5.1.5 on 2025-10-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_заявка'),
    ]

    operations = [
        migrations.AlterField(
            model_name='пользователь',
            name='Роль',
            field=models.CharField(choices=[('user', 'Пользователь'), ('superuser', 'Суперюзер')], default='user', max_length=50),
        ),
    ]
