# Generated by Django 5.1.5 on 2025-10-13 16:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_alter_пользователь_роль'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='выплаты',
            options={'verbose_name': 'Выплата', 'verbose_name_plural': 'Выплаты'},
        ),
        migrations.AlterModelOptions(
            name='документ',
            options={'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.AddField(
            model_name='выплаты',
            name='банк_получателя',
            field=models.CharField(blank=True, max_length=255, verbose_name='Банк получателя'),
        ),
        migrations.AddField(
            model_name='выплаты',
            name='дата_выплаты',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выплаты'),
        ),
        migrations.AddField(
            model_name='выплаты',
            name='дата_создания',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='выплаты',
            name='заявка',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.заявка', verbose_name='Связанная заявка'),
        ),
        migrations.AddField(
            model_name='выплаты',
            name='код_выплаты',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Код выплаты'),
        ),
        migrations.AddField(
            model_name='выплаты',
            name='назначение_платежа',
            field=models.TextField(blank=True, verbose_name='Назначение платежа'),
        ),
        migrations.AddField(
            model_name='выплаты',
            name='расчетный_счет',
            field=models.CharField(blank=True, max_length=20, verbose_name='Расчетный счет'),
        ),
        migrations.AddField(
            model_name='документ',
            name='выплата',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.выплаты', verbose_name='Связанная выплата'),
        ),
        migrations.AddField(
            model_name='документ',
            name='комментарий',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='документ',
            name='файл',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/', verbose_name='Файл документа'),
        ),
        migrations.AlterField(
            model_name='выплаты',
            name='Документ',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.документ'),
        ),
        migrations.AlterField(
            model_name='выплаты',
            name='Статус',
            field=models.CharField(choices=[('ожидает', 'Ожидает выплаты'), ('выплачено', 'Выплачено'), ('отменено', 'Отменено')], default='ожидает', max_length=50),
        ),
    ]
