# Generated by Django 5.1.5 on 2025-10-13 17:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_alter_выплаты_options_alter_документ_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='выплаты',
            name='Вид',
        ),
        migrations.RemoveField(
            model_name='выплаты',
            name='Документ',
        ),
        migrations.RemoveField(
            model_name='выплаты',
            name='Статус',
        ),
        migrations.RemoveField(
            model_name='выплаты',
            name='Сумма',
        ),
        migrations.RemoveField(
            model_name='выплаты',
            name='банк_получателя',
        ),
        migrations.RemoveField(
            model_name='выплаты',
            name='дата_выплаты',
        ),
        migrations.RemoveField(
            model_name='выплаты',
            name='расчетный_счет',
        ),
        migrations.AddField(
            model_name='выплаты',
            name='дата_выполнения',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выполнения'),
        ),
        migrations.AddField(
            model_name='выплаты',
            name='инн',
            field=models.CharField(default='0000000000', max_length=10, verbose_name='ИНН'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='выплаты',
            name='полное_наименование',
            field=models.CharField(default='Временное название организации', max_length=200, verbose_name='Полное наименование организации'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='выплаты',
            name='счет_получателя',
            field=models.CharField(default='00000000000000000000', max_length=20, verbose_name='Счет получателя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='выплаты',
            name='дата_создания',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='документ',
            name='выплата',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='связанные_документы', to='index.выплаты', verbose_name='Связанная выплата'),
        ),
        migrations.AddField(
            model_name='выплаты',
            name='вид',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.видывыплат', verbose_name='Вид выплаты'),
        ),
        migrations.AddField(
            model_name='выплаты',
            name='документ',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.документ', verbose_name='Документ'),
        ),
        migrations.AddField(
            model_name='выплаты',
            name='статус',
            field=models.CharField(choices=[('ожидает', 'Ожидает выплаты'), ('выплачено', 'Выплачено'), ('отменено', 'Отменено')], default='ожидает', max_length=50, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='выплаты',
            name='сумма',
            field=models.DecimalField(decimal_places=2, default='00000000000000000000', max_digits=15, verbose_name='Сумма'),
            preserve_default=False,
        ),
    ]
