# Generated by Django 5.1.5 on 2025-10-13 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_remove_выплаты_вид_remove_выплаты_документ_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='выплаты',
            name='заблокировано',
            field=models.BooleanField(default=False, verbose_name='Заблокировано для изменений'),
        ),
    ]
