# Generated by Django 5.1.5 on 2025-10-13 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_выплаты_заблокировано'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='выплаты',
            name='документ',
        ),
        migrations.AddField(
            model_name='выплаты',
            name='документ_создан',
            field=models.BooleanField(default=False, verbose_name='Документ создан'),
        ),
        migrations.DeleteModel(
            name='Документ',
        ),
    ]
