# Generated by Django 5.1.5 on 2025-10-14 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_remove_выплаты_документ_выплаты_документ_создан_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ОжидаемаяСуммаВыплат',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('год', models.IntegerField(verbose_name='Год')),
                ('месяц', models.IntegerField(verbose_name='Месяц')),
                ('ожидаемая_сумма', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Ожидаемая сумма выплат')),
                ('дата_создания', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Ожидаемая сумма выплат',
                'verbose_name_plural': 'Ожидаемые суммы выплат',
                'unique_together': {('год', 'месяц')},
            },
        ),
    ]
