# Generated by Django 5.1.5 on 2025-10-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_ожидаемаясуммавыплат'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ожидаемаясуммавыплат',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='ожидаемаясуммавыплат',
            name='ожидаемая_сумма_год',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Ожидаемая сумма за год'),
        ),
        migrations.AlterField(
            model_name='ожидаемаясуммавыплат',
            name='год',
            field=models.IntegerField(unique=True, verbose_name='Год'),
        ),
        migrations.RemoveField(
            model_name='ожидаемаясуммавыплат',
            name='месяц',
        ),
        migrations.RemoveField(
            model_name='ожидаемаясуммавыплат',
            name='ожидаемая_сумма',
        ),
    ]
