# Generated by Django 5.1.5 on 2025-10-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_alter_ожидаемаясуммавыплат_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='видывыплат',
            options={'verbose_name': 'Вид выплаты', 'verbose_name_plural': 'Виды выплат'},
        ),
        migrations.AlterModelOptions(
            name='ожидаемаясуммавыплат',
            options={'ordering': ['-год'], 'verbose_name': 'Ожидаемая сумма выплат', 'verbose_name_plural': 'Ожидаемые суммы выплат'},
        ),
        migrations.AlterModelOptions(
            name='организация',
            options={'verbose_name': 'Организация', 'verbose_name_plural': 'Организации'},
        ),
        migrations.AlterModelOptions(
            name='отдел',
            options={'verbose_name': 'Отдел', 'verbose_name_plural': 'Отделы'},
        ),
        migrations.AlterModelOptions(
            name='пользователь',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='типыдокументов',
            options={'verbose_name': 'Тип документа', 'verbose_name_plural': 'Типы документов'},
        ),
        migrations.CreateModel(
            name='ОтчетВыплат',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('название', models.CharField(max_length=200, verbose_name='Название отчета')),
                ('дата_создания', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('дата_начала', models.DateField(verbose_name='Дата начала периода')),
                ('дата_окончания', models.DateField(verbose_name='Дата окончания периода')),
                ('фильтр_статус', models.CharField(default='выплачено', max_length=20, verbose_name='Фильтр по статусу')),
                ('общая_сумма', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Общая сумма выплат')),
                ('количество_выплат', models.IntegerField(verbose_name='Количество выплат')),
                ('организации', models.ManyToManyField(blank=True, to='index.организация', verbose_name='Организации')),
            ],
            options={
                'verbose_name': 'Отчет выплат',
                'verbose_name_plural': 'Отчеты выплат',
                'ordering': ['-дата_создания'],
            },
        ),
    ]
