# Generated by Django 5.1.5 on 2025-10-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_alter_видывыплат_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='заявка',
            name='дата_отклонения',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отклонения'),
        ),
        migrations.AddField(
            model_name='заявка',
            name='комментарий_отклонения',
            field=models.TextField(blank=True, null=True, verbose_name='Причина отклонения'),
        ),
    ]
