# Generated by Django 5.1.5 on 2025-10-16 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_заявка_дата_отклонения_заявка_комментарий_отклонения'),
    ]

    operations = [
        migrations.AlterField(
            model_name='выплаты',
            name='заявка',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='связанные_выплаты', to='index.заявка', verbose_name='Связанная заявка'),
        ),
    ]
