# Generated by Django 5.1.5 on 2025-10-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_alter_выплаты_заявка'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('название', models.CharField(max_length=200, verbose_name='Название отчета')),
                ('дата_создания', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('дата_начала', models.DateField(verbose_name='Дата начала периода')),
                ('дата_окончания', models.DateField(verbose_name='Дата окончания периода')),
                ('плановая_сумма_периода', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Плановая сумма за период')),
                ('фактическая_сумма', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Фактическая сумма выплат')),
                ('количество_выплат', models.IntegerField(verbose_name='Количество выплат')),
                ('отклонение', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Отклонение')),
                ('процент_выполнения', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Процент выполнения плана')),
                ('данные_графика', models.JSONField(blank=True, default=dict, verbose_name='Данные для графиков')),
                ('организации', models.ManyToManyField(blank=True, to='index.организация', verbose_name='Организации')),
            ],
            options={
                'verbose_name': 'Аналитический отчет',
                'verbose_name_plural': 'Аналитические отчеты',
                'ordering': ['-дата_создания'],
            },
        ),
    ]
