# Generated by Django 5.1.5 on 2025-10-16 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0016_analyticalreport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analyticalreport',
            options={'ordering': ['-дата_создания'], 'verbose_name': 'Аналитический отчет планировщика', 'verbose_name_plural': 'Аналитические отчеты планировщика'},
        ),
        migrations.AddField(
            model_name='analyticalreport',
            name='макс_выплата',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Максимальная выплата'),
        ),
        migrations.AddField(
            model_name='analyticalreport',
            name='мин_выплата',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Минимальная выплата'),
        ),
        migrations.AddField(
            model_name='analyticalreport',
            name='средний_чек',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Средний чек'),
        ),
    ]
