# Generated by Django 5.1.5 on 2025-10-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0017_alter_analyticalreport_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analyticalreport',
            options={},
        ),
        migrations.RemoveField(
            model_name='analyticalreport',
            name='макс_выплата',
        ),
        migrations.RemoveField(
            model_name='analyticalreport',
            name='мин_выплата',
        ),
        migrations.RemoveField(
            model_name='analyticalreport',
            name='средний_чек',
        ),
        migrations.AddField(
            model_name='analyticalreport',
            name='прогноз_на_остаток_года',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Прогноз на остаток года'),
        ),
        migrations.AddField(
            model_name='analyticalreport',
            name='риск_невыполнения_плана',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Риск невыполнения плана %'),
        ),
        migrations.AddField(
            model_name='analyticalreport',
            name='эффективность_использования_бюджета',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Эффективность использования бюджета %'),
        ),
    ]
