# Generated by Django 5.1.5 on 2025-10-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0018_alter_analyticalreport_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ОтчетПланировщика',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('название', models.CharField(max_length=200, verbose_name='Название отчета')),
                ('дата_создания', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('дата_начала', models.DateField(verbose_name='Дата начала периода')),
                ('дата_окончания', models.DateField(verbose_name='Дата окончания периода')),
                ('ожидаемая_сумма_периода', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Ожидаемая сумма за период')),
                ('фактическая_сумма_периода', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Фактическая сумма за период')),
                ('отклонение_суммы', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Отклонение по сумме')),
                ('процент_выполнения_плана', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Процент выполнения плана')),
                ('количество_выплат', models.IntegerField(default=0, verbose_name='Количество выплат')),
                ('данные_графика', models.JSONField(blank=True, default=dict, verbose_name='Данные для графика')),
            ],
            options={
                'verbose_name': 'Отчет планировщика',
                'verbose_name_plural': 'Отчеты планировщика',
                'ordering': ['-дата_создания'],
            },
        ),
        migrations.DeleteModel(
            name='AnalyticalReport',
        ),
    ]
