# Generated by Django 5.1.5 on 2026-03-02 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0019_отчетпланировщика_delete_analyticalreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='СметаПроект',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('название', models.CharField(max_length=200, verbose_name='Название проекта')),
                ('описание', models.TextField(blank=True, verbose_name='Описание проекта')),
                ('запрашиваемая_сумма', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Запрашиваемая сумма')),
            ],
            options={
                'verbose_name': 'Проект сметы',
                'verbose_name_plural': 'Проекты сметы',
            },
        ),
        migrations.CreateModel(
            name='СметаЗатрат',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('название', models.CharField(max_length=200, verbose_name='Название сметы')),
                ('год', models.IntegerField(verbose_name='Плановый год')),
                ('дата_создания', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('дата_отправки', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки')),
                ('дата_рассмотрения', models.DateTimeField(blank=True, null=True, verbose_name='Дата рассмотрения')),
                ('документ_сметы', models.FileField(help_text='Загрузите документ с электронной печатью администрации', upload_to='smeti/%Y/%m/', verbose_name='Документ со сметой (с печатью)')),
                ('общая_сумма', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Общая сумма сметы')),
                ('статус', models.CharField(choices=[('черновик', 'Черновик'), ('отправлена', 'Отправлена в бюджетный отдел'), ('на_рассмотрении', 'На рассмотрении'), ('одобрена', 'Одобрена'), ('отклонена', 'Отклонена'), ('требует_доработки', 'Требует доработки')], default='черновик', max_length=20, verbose_name='Статус')),
                ('комментарий_администрации', models.TextField(blank=True, verbose_name='Комментарий администрации')),
                ('комментарий_бюджетного_отдела', models.TextField(blank=True, verbose_name='Комментарий бюджетного отдела')),
                ('организация', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='отправленные_сметы', to='index.организация', verbose_name='Организация')),
                ('получатель', models.ForeignKey(blank=True, limit_choices_to={'Отдел__Название': 'Бюджетный отдел'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='полученные_сметы', to='index.пользователь', verbose_name='Получатель (специалист)')),
                ('созданные_заявки', models.ManyToManyField(blank=True, related_name='исходная_смета', to='index.заявка', verbose_name='Созданные заявки')),
                ('проекты', models.ManyToManyField(blank=True, to='index.сметапроект', verbose_name='Проекты')),
            ],
            options={
                'verbose_name': 'Смета затрат',
                'verbose_name_plural': 'Сметы затрат',
                'ordering': ['-дата_создания'],
            },
        ),
    ]
