# Generated by Django 5.1.5 on 2026-03-02 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0020_сметапроект_сметазатрат'),
    ]

    operations = [
        migrations.CreateModel(
            name='ШаблонДокумента',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('название', models.CharField(max_length=200, verbose_name='Название шаблона')),
                ('содержание', models.TextField(help_text='Используйте {поле} для подстановки данных', verbose_name='Содержание шаблона')),
                ('описание', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Шаблон документа',
                'verbose_name_plural': 'Шаблоны документов',
            },
        ),
        migrations.AlterField(
            model_name='сметазатрат',
            name='документ_сметы',
            field=models.FileField(blank=True, help_text='Загрузите документ с электронной печатью администрации', null=True, upload_to='smeti/%Y/%m/', verbose_name='Документ со сметой (с печатью)'),
        ),
        migrations.CreateModel(
            name='СгенерированныйДокумент',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('название', models.CharField(max_length=200, verbose_name='Название документа')),
                ('содержание', models.TextField(verbose_name='Содержание')),
                ('дата_создания', models.DateTimeField(auto_now_add=True)),
                ('смета', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='документы', to='index.сметазатрат')),
            ],
            options={
                'verbose_name': 'Сгенерированный документ',
                'verbose_name_plural': 'Сгенерированные документы',
            },
        ),
    ]
