# Generated by Django 5.1.5 on 2026-03-02 13:52

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0021_шаблондокумента_alter_сметазатрат_документ_сметы_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='сметазатрат',
            options={'verbose_name': 'Смета затрат', 'verbose_name_plural': 'Сметы затрат'},
        ),
        migrations.RemoveField(
            model_name='сметазатрат',
            name='дата_рассмотрения',
        ),
        migrations.RemoveField(
            model_name='сметазатрат',
            name='дата_создания',
        ),
        migrations.RemoveField(
            model_name='сметазатрат',
            name='документ_сметы',
        ),
        migrations.RemoveField(
            model_name='сметазатрат',
            name='комментарий_администрации',
        ),
        migrations.RemoveField(
            model_name='сметазатрат',
            name='комментарий_бюджетного_отдела',
        ),
        migrations.RemoveField(
            model_name='сметазатрат',
            name='общая_сумма',
        ),
        migrations.RemoveField(
            model_name='сметазатрат',
            name='получатель',
        ),
        migrations.RemoveField(
            model_name='сметазатрат',
            name='проекты',
        ),
        migrations.RemoveField(
            model_name='сметазатрат',
            name='созданные_заявки',
        ),
        migrations.AddField(
            model_name='сметазатрат',
            name='документ',
            field=models.FileField(default='t.txt', upload_to='smeti/%Y/%m/', verbose_name='Документ с печатью'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='сметазатрат',
            name='комментарий',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='сметазатрат',
            name='год',
            field=models.IntegerField(verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='сметазатрат',
            name='дата_отправки',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 3, 2, 13, 52, 37, 44424, tzinfo=datetime.timezone.utc), verbose_name='Дата отправки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='сметазатрат',
            name='организация',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.организация', verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='сметазатрат',
            name='статус',
            field=models.CharField(choices=[('отправлена', 'Отправлена'), ('одобрена', 'Одобрена'), ('отклонена', 'Отклонена')], default='отправлена', max_length=20),
        ),
    ]
