# Generated by Django 5.1.5 on 2026-03-02 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0022_alter_сметазатрат_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ШаблонДокумента',
        ),
        migrations.AlterModelOptions(
            name='сметазатрат',
            options={'ordering': ['-дата_создания'], 'verbose_name': 'Смета затрат', 'verbose_name_plural': 'Сметы затрат'},
        ),
        migrations.AddField(
            model_name='сметазатрат',
            name='дата_создания',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 3, 2, 14, 18, 5, 925214, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='сметазатрат',
            name='общая_сумма',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Общая сумма сметы'),
        ),
        migrations.AddField(
            model_name='сметазатрат',
            name='проекты',
            field=models.ManyToManyField(blank=True, to='index.сметапроект', verbose_name='Проекты'),
        ),
        migrations.AlterField(
            model_name='сметазатрат',
            name='год',
            field=models.IntegerField(verbose_name='Плановый год'),
        ),
        migrations.AlterField(
            model_name='сметазатрат',
            name='дата_отправки',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки'),
        ),
        migrations.AlterField(
            model_name='сметазатрат',
            name='документ',
            field=models.FileField(blank=True, null=True, upload_to='smeti/%Y/%m/', verbose_name='Документ с печатью'),
        ),
        migrations.AlterField(
            model_name='сметазатрат',
            name='статус',
            field=models.CharField(choices=[('черновик', 'Черновик'), ('отправлена', 'Отправлена в бюджетный отдел'), ('одобрена', 'Одобрена'), ('отклонена', 'Отклонена')], default='черновик', max_length=20, verbose_name='Статус'),
        ),
    ]
