# Generated by Django 5.1.5 on 2026-03-03 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0023_delete_шаблондокумента_alter_сметазатрат_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='сметазатрат',
            name='документ',
        ),
        migrations.AlterField(
            model_name='сгенерированныйдокумент',
            name='смета',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='сгенерированные_документы', to='index.сметазатрат'),
        ),
        migrations.CreateModel(
            name='ДокументСметы',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('тип', models.CharField(choices=[('smeta', 'Смета с печатью'), ('zayavka', 'Письмо-заявка'), ('dogovor', 'Соглашение о сотрудничестве')], max_length=20, verbose_name='Тип документа')),
                ('название', models.CharField(max_length=200, verbose_name='Название')),
                ('файл', models.FileField(upload_to='smeti_docs/%Y/%m/', verbose_name='PDF файл')),
                ('дата_создания', models.DateTimeField(auto_now_add=True)),
                ('смета', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='документы_сметы', to='index.сметазатрат')),
            ],
            options={
                'verbose_name': 'Документ сметы',
                'verbose_name_plural': 'Документы сметы',
                'ordering': ['-дата_создания'],
            },
        ),
    ]
