# Generated by Django 5.1.5 on 2026-03-03 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0024_remove_сметазатрат_документ_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='документсметы',
            name='файл',
        ),
        migrations.AddField(
            model_name='документсметы',
            name='pdf_data',
            field=models.BinaryField(default=b'', verbose_name='PDF данные'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='документсметы',
            name='смета',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='документы', to='index.сметазатрат'),
        ),
        migrations.AlterField(
            model_name='документсметы',
            name='тип',
            field=models.CharField(choices=[('smeta', 'Смета с печатью'), ('zayavka', 'Письмо-заявка')], max_length=20, verbose_name='Тип документа'),
        ),
    ]
