# Generated by Django 5.1.5 on 2026-03-05 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0025_remove_документсметы_файл_документсметы_pdf_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ДокументЗаявки',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('тип', models.CharField(choices=[('dogovor', 'Трудовой договор'), ('prikaz', 'Приказ'), ('tabel', 'Табель учёта времени'), ('akt', 'Акт выполненных работ'), ('schet', 'Счёт'), ('raschet', 'Расчётный лист'), ('vedomost', 'Платёжная ведомость'), ('other', 'Прочее')], max_length=20, verbose_name='Тип документа')),
                ('название', models.CharField(max_length=200, verbose_name='Название')),
                ('файл', models.FileField(upload_to='zayavki_docs/%Y/%m/', verbose_name='Файл')),
                ('описание', models.TextField(blank=True, verbose_name='Описание')),
                ('дата_загрузки', models.DateTimeField(auto_now_add=True)),
                ('заявка', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='документы', to='index.заявка')),
            ],
            options={
                'verbose_name': 'Документ заявки',
                'verbose_name_plural': 'Документы заявки',
                'ordering': ['-дата_загрузки'],
            },
        ),
    ]
