# Generated by Django 5.1.5 on 2026-03-10 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0026_документзаявки'),
    ]

    operations = [
        migrations.CreateModel(
            name='СметаБюджета',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('год', models.IntegerField(verbose_name='Год')),
                ('дата_создания', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('дата_обновления', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('статус', models.CharField(choices=[('черновик', 'Черновик'), ('утверждена', 'Утверждена'), ('отправлена', 'Отправлена')], default='черновик', max_length=20, verbose_name='Статус')),
                ('создана_на_основе_выплат', models.BooleanField(default=False, verbose_name='Создана на основе выплат')),
                ('исходный_год', models.IntegerField(blank=True, null=True, verbose_name='Исходный год выплат')),
                ('общая_сумма', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Общая сумма')),
                ('смета_администрации', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.сметазатрат', verbose_name='Смета от администрации')),
                ('создатель', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.пользователь', verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Смета бюджета',
                'verbose_name_plural': 'Сметы бюджета',
                'ordering': ['-год', '-дата_создания'],
            },
        ),
        migrations.CreateModel(
            name='ДокументСметыБюджета',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('тип', models.CharField(choices=[('smeta', 'Смета расходов'), ('pismo', 'Письмо-заявка'), ('otchet', 'Отчет')], max_length=20, verbose_name='Тип документа')),
                ('название', models.CharField(max_length=200, verbose_name='Название')),
                ('pdf_data', models.BinaryField(verbose_name='PDF данные')),
                ('дата_создания', models.DateTimeField(auto_now_add=True)),
                ('смета', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='документы', to='index.сметабюджета')),
            ],
            options={
                'verbose_name': 'Документ сметы',
                'verbose_name_plural': 'Документы сметы',
            },
        ),
        migrations.CreateModel(
            name='СтатьяСметы',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('название', models.CharField(max_length=200, verbose_name='Название статьи')),
                ('тип', models.CharField(choices=[('zp', 'Заработная плата'), ('kommunalka', 'Коммунальные услуги'), ('remont', 'Ремонтные работы'), ('oborudovanie', 'Приобретение оборудования'), ('soft', 'Программное обеспечение'), ('transport', 'Транспортные расходы'), ('svyaz', 'Связь и интернет'), ('kanc', 'Канцелярские товары'), ('other', 'Прочее')], default='other', max_length=20, verbose_name='Тип')),
                ('сумма', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма')),
                ('описание', models.TextField(blank=True, verbose_name='Описание')),
                ('основано_на_выплатах', models.BooleanField(default=False)),
                ('количество_выплат', models.IntegerField(default=0, verbose_name='Количество выплат')),
                ('смета', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='статьи', to='index.сметабюджета')),
            ],
            options={
                'verbose_name': 'Статья сметы',
                'verbose_name_plural': 'Статьи сметы',
            },
        ),
    ]
