# Generated by Django 5.1.5 on 2026-03-10 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0027_сметабюджета_документсметыбюджета_статьясметы'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='сметабюджета',
            name='смета_администрации',
        ),
        migrations.RemoveField(
            model_name='сметабюджета',
            name='создатель',
        ),
        migrations.RemoveField(
            model_name='статьясметы',
            name='смета',
        ),
        migrations.CreateModel(
            name='СметаФБП',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('год', models.IntegerField(verbose_name='Плановый год')),
                ('дата_создания', models.DateTimeField(auto_now_add=True)),
                ('дата_обновления', models.DateTimeField(auto_now=True)),
                ('статус', models.CharField(choices=[('черновик', 'Черновик'), ('утверждена', 'Утверждена'), ('отправлена', 'Отправлена')], default='черновик', max_length=20)),
                ('создана_на_основе_выплат_за_год', models.IntegerField(blank=True, null=True, verbose_name='Год выплат')),
                ('общая_сумма', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('создатель', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='index.пользователь')),
            ],
            options={
                'verbose_name': 'Смета ФБП',
                'verbose_name_plural': 'Сметы ФБП',
            },
        ),
        migrations.CreateModel(
            name='ДокументСметыФБП',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('тип', models.CharField(choices=[('smeta', 'Смета расходов'), ('pismo', 'Письмо-заявка')], max_length=20)),
                ('название', models.CharField(max_length=200)),
                ('pdf_data', models.BinaryField()),
                ('дата_создания', models.DateTimeField(auto_now_add=True)),
                ('смета', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='документы', to='index.сметафбп')),
            ],
            options={
                'verbose_name': 'Документ сметы ФБП',
                'verbose_name_plural': 'Документы смет ФБП',
            },
        ),
        migrations.CreateModel(
            name='СтатьяСметыФБП',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('название', models.CharField(max_length=200)),
                ('тип', models.CharField(choices=[('zp', 'Заработная плата'), ('kommunalka', 'Коммунальные услуги'), ('remont', 'Ремонтные работы'), ('oborudovanie', 'Приобретение оборудования'), ('soft', 'Программное обеспечение'), ('transport', 'Транспортные расходы'), ('svyaz', 'Связь и интернет'), ('kanc', 'Канцелярские товары'), ('other', 'Прочее')], default='other', max_length=20)),
                ('сумма', models.DecimalField(decimal_places=2, max_digits=15)),
                ('описание', models.TextField(blank=True)),
                ('основано_на_выплатах', models.BooleanField(default=False)),
                ('количество_выплат', models.IntegerField(default=0)),
                ('исходная_организация', models.CharField(blank=True, max_length=200, verbose_name='Организация')),
                ('смета', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='статьи', to='index.сметафбп')),
            ],
            options={
                'verbose_name': 'Статья сметы ФБП',
                'verbose_name_plural': 'Статьи смет ФБП',
            },
        ),
        migrations.DeleteModel(
            name='ДокументСметыБюджета',
        ),
        migrations.DeleteModel(
            name='СметаБюджета',
        ),
        migrations.DeleteModel(
            name='СтатьяСметы',
        ),
    ]
