# Generated by Django 5.1.5 on 2026-03-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0028_remove_сметабюджета_смета_администрации_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='документсметыфбп',
            options={},
        ),
        migrations.AddField(
            model_name='сметазатрат',
            name='дата_рассмотрения',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата рассмотрения'),
        ),
    ]
