# Generated by Django 5.2.7 on 2026-05-09 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0029_alter_документсметыфбп_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ОтчетПоЗаявкам',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('название', models.CharField(max_length=255, verbose_name='Название отчета')),
                ('дата_создания', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('дата_начала', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('дата_окончания', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('фильтр_статус', models.CharField(blank=True, max_length=50, null=True, verbose_name='Фильтр по статусу')),
                ('фильтр_вид_выплаты', models.IntegerField(blank=True, null=True, verbose_name='Фильтр по виду выплаты')),
                ('количество_заявок', models.IntegerField(default=0, verbose_name='Количество заявок')),
                ('общая_сумма', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Общая сумма')),
                ('количество_новых', models.IntegerField(default=0, verbose_name='Новых')),
                ('количество_принятых', models.IntegerField(default=0, verbose_name='Принятых')),
                ('количество_отклоненных', models.IntegerField(default=0, verbose_name='Отклоненных')),
                ('данные', models.JSONField(blank=True, default=dict, verbose_name='Данные отчета')),
                ('файл', models.FileField(blank=True, null=True, upload_to='reports/applications/', verbose_name='Файл отчета')),
                ('создатель', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='отчеты_заявки', to='index.пользователь')),
            ],
            options={
                'verbose_name': 'Отчет по заявкам',
                'verbose_name_plural': 'Отчеты по заявкам',
                'ordering': ['-дата_создания'],
            },
        ),
    ]
